-- WARNING: Do NOT edit this file. It was generated by make.

local mt_utils = require("ex-colors.utils.metatable")

local M = {
  hlgroup = require("ex-colors.presets.hlgroup"),
  pattern = require("ex-colors.presets.pattern"),
  relinker = require("ex-colors.presets.relinker"),
  recommended = {},
}

M.recommended.included_hlgroups = mt_utils.new_addable(
  M.hlgroup.builtin.default
    + M.hlgroup.builtin.naming_conventions
    + M.hlgroup.builtin.diagnostic
    + M.hlgroup.builtin.treesitter
    + M.hlgroup.builtin.lsp
    + M.hlgroup.builtin.lsp_semantic_highlight
    + M.hlgroup.convention.ansi_colors
)

M.recommended.excluded_patterns = mt_utils.new_addable(
  M.pattern.treesitter_filetype_captures
    + M.pattern.convention.ansi_color_prefixes
)

function M.recommended.relinker(hl_name)
  hl_name = M.relinker.no_typo(hl_name)
  hl_name = M.relinker.no_superseded(hl_name)
  hl_name = M.relinker.no_TS_prefixed(hl_name)
  -- NOTE: It might be undesirable for general users to exclude
  -- lsp-semantic-highlight.
  -- hl_name = M.no_lsp_semantic_highlight(hl_name)
  return hl_name
end

local mt = {
  __index = function(_, k)
    return error("undefined preset: " .. k)
  end,
  __newindex = function()
    error("presets are read-only")
  end,
}

for _, v in pairs(M) do
  setmetatable(v, mt)
end

return setmetatable(M, mt)
