-- WARNING: Do NOT edit this file. It was generated by make.
local M = {
  relinker = require("ex-colors.presets.relinker"),
}

local mt = {
  __index = function(_, k)
    return error("undefined preset: " .. k)
  end,
  __newindex = function()
    error("presets are read-only")
  end,
}

for _, v in pairs(M) do
  setmetatable(v, mt)
end

return setmetatable(M, mt)
